feat(infra): github actions checks if code builds before merging

diff --git a/.github/workflows/style-and-lint.yaml b/.github/workflows/style-and-lint.yaml
--- a/.github/workflows/style-and-lint.yaml
+++ b/.github/workflows/style-and-lint.yaml
@@ -20,6 +20,14 @@ jobs:
 
     - name: Install dependencies
       run: npm install
+    
+    - name: Run build check
+      run: |
+        npm run build
+        if [ $? -ne 0 ]; then
+          echo "Code failed to build. Please fix the issues before merging."
+          exit 1
+        fi
 
     - name: Run style check
       run: |
